### ISSUE TITLE
Código repetido entre el AND y OR

### ISSUE THREAD

**Issue by nnydjesus** [damianlattenero/aterrizar.com#10]
Lo unico que tienen de distinto es el string "and"  y "or", podrían buscar una mejor abstracción.

Otra sugerencia que les puedo dar es que podrían agrupar varias clases en un solo archivo, xtend te permite hacer eso (obviamente esas clases deberían estar muy bien relacionadas y no tener mucho código )

Por ejemplo, en su caso quedaría algo asi:

![screen shot 2016-04-25 at 12 30 58 am](https://cloud.githubusercontent.com/assets/1201972/14773160/20e22720-0a7d-11e6-9fe1-01af364783fc.png)

Ahora ven mejor el problema del código repetido?

**Comment by damianlattenero** [comment]
cerrado
