### ISSUE TITLE
Mucho código repetido en los Services

### ISSUE THREAD

**Issue by nnydjesus** [damianlattenero/aterrizar.com#12]
Tienen que buscar una abstracción para esto también.

![screen shot 2016-04-25 at 12 48 56 am](https://cloud.githubusercontent.com/assets/1201972/14773355/83946dfe-0a7f-11e6-9dd7-ef29face687e.png)

![screen shot 2016-04-25 at 12 48 49 am](https://cloud.githubusercontent.com/assets/1201972/14773357/84acceac-0a7f-11e6-98ca-766b289da079.png)

![screen shot 2016-04-25 at 12 48 37 am](https://cloud.githubusercontent.com/assets/1201972/14773359/862fd1de-0a7f-11e6-93ef-e492c5591e1a.png)

**Comment by damianlattenero** [comment]
cerrado
