### ISSUE TITLE
Responsabilidad del AsientoHome

### ISSUE THREAD

**Issue by nnydjesus** [damianlattenero/aterrizar.com#13]
Porque el home sabe de reservarAsientos?

![screen shot 2016-04-25 at 12 53 18 am](https://cloud.githubusercontent.com/assets/1201972/14773420/3347d218-0a80-11e6-9dca-0c6b15b45256.png)

La **Home** no debería saber de eso... solo debería interactuar con la persistencia, par eso esta el **Servicio**

**Comment by damianlattenero** [comment]
Cerrado
