### ISSUE TITLE
Código repetido en los Homes 

### ISSUE THREAD

**Issue by nnydjesus** [damianlattenero/aterrizar.com#8]
![screen shot 2016-04-25 at 12 15 33 am](https://cloud.githubusercontent.com/assets/1201972/14773003/deaab004-0a7a-11e6-8035-0bc42a7d9e22.png)

Que cambia en esos tres métodos? Como podrían utilizar el mismo método para guardar todos los objetos?

Aha hay otro caso:

![screen shot 2016-04-25 at 12 18 06 am](https://cloud.githubusercontent.com/assets/1201972/14773030/4333940a-0a7b-11e6-8383-dd0a70466ef7.png)

![screen shot 2016-04-25 at 12 17 57 am](https://cloud.githubusercontent.com/assets/1201972/14773031/4528bd58-0a7b-11e6-8c70-753751795865.png)

![screen shot 2016-04-25 at 12 06 00 am](https://cloud.githubusercontent.com/assets/1201972/14773032/478d49e2-0a7b-11e6-8040-8a874f088362.png)

Pueden identificar que cosas se repiten o mejor dicho cuales son las diferencias y si pueden parametrizarse?

**Comment by damianlattenero** [comment]
cerrado
