### ISSUE TITLE
Búsqueda - Tener HQL en el código de dominio

### ISSUE THREAD

**Issue by nnydjesus** [damianlattenero/aterrizar.com#9]
Porque generan el hql en el código de dominio?

![screen shot 2016-04-25 at 12 21 43 am](https://cloud.githubusercontent.com/assets/1201972/14773083/d959134c-0a7b-11e6-83b4-b122a690150f.png)

Para que no haga tanto ruido, las clases de la búsqueda podrían estar en otro paquete separado del dominio. Si no tendrían que persistirse estarían en ese package?

**Comment by damianlattenero** [comment]
cerrado
